### PR TITLE
Add Codec.Serialise instances

### PR DESCRIPTION
**Pull request by imalsogreg**
Willing to add `serialise`? :)

### CODE REVIEW

**Comment by k0001** [comment]
Ah, nice, thanks.

I think, though, I'd like to call the flag and module "cbor" instead of "serialise". The reason for this this is that "serialise" means already too many things, and it doesn't help with discoverability. Perhaps we can add a comment to the flag and module saying "cbor serialization through the serialise library".

**Comment by imalsogreg** [comment]
Good ideas :) done

**Comment by k0001** [comment]
@imalsogreg I changed the serialization format a bit so that it takes one less byte. No reason to waste that precious space :)

Thanks!

Also, I changed `release.nix` so that it tracks the latest `nixos-17.09` channel, whatever the latest commit might be. This technically leads to less reproducible builds by default (i.e., unless you override the `nixpkgs` argument to `release.nix`), but since `nixos-17.09` is not supposed to suddenly add breaking changes, then it should be fine. The benefit is that Travis builds run faster, since the upstream channel always has binary artifacts available.

**Comment by imalsogreg** [comment]
Sweet. Thanks for the fix! Glad to have this in.

**Pull request merged**
